#!/bin/sh

# colorizing grep. essential really.
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# system monitoring
alias topmem='ps auxf | sort -nr -k 4 | head -5'
alias topcpu='ps auxf | sort -nr -k 3 | head -5'
